name:                lc
version:             0.1.0.0
github:              d-dorazio/lc
license:             MIT
author:              d-dorazio
maintainer:          d.dorazio96@gmail.com
copyright:           MIT

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:             Lambda Calculus
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/d-dorazio/lc#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- haskeline
- megaparsec
- mtl
- pretty

ghc-options:
- -Wall
- -fwarn-tabs

library:
  source-dirs: src

executables:
  lc:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lc
    - optparse-applicative

tests:
  lc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - lc
    - QuickCheck
    - safe
